### PR TITLE
[DO NOT MERGE] PIM-254: Refactor Export Heroku App

### PR DESCRIPTION
**Pull request by clawyq**
Seeing how the current code is so unmaintainable, I feel it is important that we get this refactor in before we can do other tasks.

If you have an extra half an hour in between meetings/tasks, or if you want a logical break (or to even just do a good deed for today), you can help contribute to the refactoring effort! I'm personally going to start by breaking down the super huge method into manageable chunks each day.

That said, the refactoring goals are:

- Maintainability - If I get hit by a bus tomorrow, can literally any other dev take over my work the next day with minimal onboarding effort?
  - key markers include but are not limited to: 
    1.    Is my function doing one thing and one thing only?
    2.    Am I repeating code that is somewhere else in the codebase?
    3.    Is my code readable? Is logic that is not immediately obvious abstracted? Avoid deep(max 3) nesting of code.
    4.    Is my code testable?
- Scalability - How easy is it to add new features to the repo? Is it general enough to support other objects (Product vs Digital Asset ahem) without tearing apart the core logic?
@danielxji6 @KimJinPang @mfullmore

### CODE REVIEW

**Comment by danielxji6** [comment]
Such a great idea!

Note: I think we want to use `propel-sfdc-connect` on this? There are a few queries that contains sub-query where I did some tweaks. Need to split the sub-query before using the pkg

**Comment by mfullmore** [comment]
I started the Export refactor a few months ago. Look at `lib/ExportProduct.js` it follows the same design that import does. Now I am admitting that Import is not the greatest design but maybe we can start with what I built.

**Comment by clawyq** [comment]
> I started the Export refactor a few months ago. Look at `lib/ExportProduct.js` it follows the same design that import does. Now I am admitting that Import is not the greatest design but maybe we can start with what I built.

I'm a little unfamiliar with the export service, so I'm wary of working on that because it doesn't have the full logic there (I don't know what cases I'm missing out if it wasn't already there). At least when starting off, most of the refactoring that I'll be doing will be literally just pulling chunks out of the large functions and making them more manageable.

When we get to the point whereby the logic has reached a healthy state, structural/behavioural changes like the ones you have started in the `/lib` can then be incorporated. How does that sound @mfullmore

**Comment by mfullmore** [comment]
> When we get to the point whereby the logic has reached a healthy state, structural/behavioural changes like the ones you have started in the `/lib` can then be incorporated. How does that sound @mfullmore

Sounds good @clawyq

**Pull request merged**
